const data = [
  {
    idFnc: "42174a90",
    numeroId: "DOQ-FNC-0919-N59",
    descriptionFNC:
      "A ce jour, le suivi des fiches de non-conformités enregistrées dans le SMQ se fait manuellement. En raison du volume des informations traitées, cela demande un temps important de mise à jour des informations, de relances des acteurs traitants et de production des statistiques relatives à l’évolution des traitements. A cela s’ajoute le risque élevé d’erreur ou de perte des données dus au traitement manuel de l’information. La nécessité d’automatiser le suivi du traitement de ces vfiches de Non-",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    dateDeclaration: "18-09-2019",
    idProcessus: "M1",
    idSource: "S0",
    statutFnc: "initier",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Observation",
    idFamille: "S1",
    id: 3,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "criterCre",
    actionCorrective: "re",
    cause: "er",
    echeances: "2019-09-19",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-18",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "er",
    libelleAt: "1",
    libelleSource: "Autre (à définir)",
    libelleProcesus: "PILOTER LA STRATEGIE"
  },
  {
    idFnc: "60cbdb40",
    numeroId: "DOQ-FNC-0919-N60",
    descriptionFNC:
      "A ce jour, le suivi des fiches de non-conformités enregistrées dans le SMQ se fait manuellement. En raison du volume des informations traitées, cela demande un temps important de mise à jour des informations, de relances des acteurs traitants et de production des statistiques relatives à l’évolution des traitements. A cela s’ajoute le risque élevé d’erreur ou de perte des données dus au traitement manuel de l’information. La nécessité d’automatiser le suivi du traitement de ces fiches de Non-",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    dateDeclaration: "18-09-2019",
    idProcessus: "M1",
    idSource: "S0",
    statutFnc: "initier",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Observation",
    idFamille: "S1",
    id: 4,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "activer",
    actionCorrective: "ze",
    cause: "ze",
    echeances: "2019-09-29",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-18",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "ze",
    libelleAt: "1",
    libelleSource: "Autre (à définir)",
    libelleProcesus: "PILOTER LA STRATEGIE"
  },
  {
    idFnc: "596befc0",
    numeroId: "DOQ-FNC-0919-N56",
    descriptionFNC:
      "cedrick cedrick  cedrick cedrick cedrick cedrick cedrick cedrick cedrick cedrick cedrick cedrick cedrick cedrick cedrick cedrick ",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    dateDeclaration: "17-09-2019",
    idProcessus: "M1",
    idSource: "S0",
    statutFnc: "initier",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Mineure",
    idFamille: "S1",
    id: 5,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "activer",
    actionCorrective: "zeze",
    cause: "zeze",
    echeances: "2019-09-27",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-18",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "ze",
    libelleAt: "1",
    libelleSource: "Autre (à définir)",
    libelleProcesus: "PILOTER LA STRATEGIE"
  },
  {
    idFnc: "a5912370",
    numeroId: "DOQ-FNC-0919-N55",
    descriptionFNC:
      "rererrerererrerererre rererre rererre rererre rererre rererre rererre rererrerererrerererre rererre rererre rererre rererre rererre rererre",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    dateDeclaration: "17-09-2019",
    idProcessus: "S4",
    idSource: "S0",
    statutFnc: "initier",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Observation",
    idFamille: "S17",
    id: 6,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "activer",
    actionCorrective: "s",
    cause: "s",
    echeances: "2019-10-06",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-18",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "s",
    libelleAt: "1",
    libelleSource: "Autre (à définir)",
    libelleProcesus: "GERER LES RESSOURCES HUMAINES"
  },
  {
    idFnc: "d552ba50",
    numeroId: "DOQ-FNC-0919-N57",
    descriptionFNC:
      " zerrtr azererzaeztze teztrzaetrzerrtr azererzaeztze teztrzaetrzerrtr azererzaeztze teztrzaetrzerrtr azererzaeztze teztrzaetrzerrtr azererzaeztze teztrzaetr",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    dateDeclaration: "17-09-2019",
    idProcessus: "S4",
    idSource: "S0",
    statutFnc: "initier",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Observation",
    idFamille: "S17",
    id: 7,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "activer",
    actionCorrective: "erer",
    cause: "erer",
    echeances: "2019-09-21",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-19",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "er",
    libelleAt: "1",
    libelleSource: "Autre (à définir)",
    libelleProcesus: "GERER LES RESSOURCES HUMAINES"
  },
  {
    idFnc: "d552ba50",
    numeroId: "DOQ-FNC-0919-N57",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    idProcessus: "S4",
    idSource: "S0",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Observation",
    idFamille: "S17",
    id: 8,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "activer",
    actionCorrective: "ze",
    cause: "ze",
    echeances: "2019-09-27",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-19",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "ze",
    libelleAt: "2"
  },
  {
    idFnc: "d552ba50",
    numeroId: "DOQ-FNC-0919-N57",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    idProcessus: "S4",
    idSource: "S0",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Observation",
    idFamille: "S17",
    id: 9,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "activer",
    actionCorrective: "sd",
    cause: "dsd",
    echeances: "2019-09-28",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-19",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "ssd",
    libelleAt: "3"
  },

  {
    idFnc: "d552ba50",
    numeroId: "DOQ-FNC-0919-N57",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    idProcessus: "S4",
    idSource: "S0",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Observation",
    idFamille: "S17",
    id: 9,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "activer",
    actionCorrective: "sd",
    cause: "dsd",
    echeances: "2019-09-28",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-19",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "ssd",
    libelleAt: "3"
  },
  {
    idFnc: "d552ba50",
    numeroId: "DOQ-FNC-0919-N57",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    idProcessus: "S4",
    idSource: "S0",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Observation",
    idFamille: "S17",
    id: 9,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "activer",
    actionCorrective: "sd",
    cause: "dsd",
    echeances: "2019-09-28",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-19",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "ssd",
    libelleAt: "3"
  },
  {
    idFnc: "d552ba50",
    numeroId: "DOQ-FNC-0919-N58",
    idInitiateur: "maikol.ahoue@bridgebankgroup.com",
    idProcessus: "S4",
    idSource: "S0",
    statutRoutage: null,
    statutEva: null,
    dateCloturePro: null,
    dateClotureDef: null,
    echeanceFnc: null,
    statutEcheance: null,
    qualification: "Observation",
    idFamille: "S17",
    id: 8,
    idActeur: "maikol.ahoue@bridgebankgroup.com",
    statut: "activer",
    actionCorrective: "ze",
    cause: "ze",
    echeances: "2019-09-27",
    idActeurDelegataire: "ahoueromeo@gmail.com",
    dateCreationAnalyse: "2019-09-19",
    resultatTraitement: null,
    dateFinAnalyse: null,
    correction: "ze",
    libelleAt: "2"
  }
];

export default data;
